export const cities = [
  { name: 'New York' },
  { name: 'Moscow' },
  { name: 'Berlin' },
  { name: 'Paris' },
  { name: 'Saint Petersburg' },
  { name: 'London' },
  { name: 'Tokyo' },
  { name: 'Beijing' },
  { name: 'Sydney' },
  { name: 'Los Angeles' },
  { name: 'Chicago' },
  { name: 'Hong Kong' },
  { name: 'Toronto' },
  { name: 'Dubai' },
  { name: 'Singapore' },
  { name: 'Mexico City' },
  { name: 'São Paulo' },
  { name: 'Madrid' },
  { name: 'Rome' },
  { name: 'Istanbul' },
  { name: 'Mumbai' },
  { name: 'Bangkok' },
  { name: 'Cairo' },
  { name: 'Seoul' },
  { name: 'Buenos Aires' },
  { name: 'Lagos' },
  { name: 'Jakarta' },
  { name: 'Kuala Lumpur' },
  { name: 'Lima' },
  { name: 'Rio de Janeiro' },
  { name: 'Johannesburg' },
  { name: 'Karachi' },
  { name: 'Baghdad' },
  { name: 'Tehran' },
  { name: 'Manila' },
  { name: 'Nairobi' },
  { name: 'Athens' },
  { name: 'Warsaw' },
  { name: 'Vienna' },
  { name: 'Lisbon' },
  { name: 'Budapest' },
  { name: 'Brussels' },
  { name: 'Copenhagen' },
  { name: 'Dublin' },
  { name: 'Oslo' },
  { name: 'Helsinki' },
  { name: 'Stockholm' },
];
